paths:
    migrations: %%PHINX_CONFIG_DIR%%/../data/migrations
        
environments:
    default_migration_table: phinxlog
    default_database: development
    production:
        adapter: mysql
        name: robinson_production
        port: 3306
                
    development:
        adapter: mysql
        host: mysql
        name: robinson_development
        user: robinson
        pass: 12345
        port: 3306
                    
    testing:
        adapter: mysql
        host: localhost
        name: robinson_testing
        
        port: 3306
